version: "3.3"
services:
  climb-api:
    build: "./api/"
    ports:
      - "8080:8080"

    restart: always
    environment:
      - MYSQL_ADDRESS=climb-db

    volumes:
      - images:/images  
    
  climb-db:
    build: "./db/"
    ports:
      - "3306:3306"

volumes:
  images:
      